[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['touch tsconfig.tsbuildinfo', 'pnpm run build']

[start]
cmd = 'node .next/standalone/server.js'
